### PR TITLE
building blessings for windows

### PR DESCRIPTION
**Pull request by sannykr**
I am trying to see if windows build works.

### CODE REVIEW

**Comment by sannykr** [comment]
@synapticarbors : I deleted the skip statement to skip windows build to see if it works for windows, but still it is not running the CI check for windows. Can you please tell me why.

**Comment by synapticarbors** [comment]
I'm not sure why appveyor isn't kicking in. @jakirkham any ideas?

**Comment by jakirkham** [comment]
Needs to be [re-rendered]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) first to enable AppVeyor.

**Comment by sannykr** [comment]
@jakirkham : Thanks. It worked after re-rendering.

**Comment by jakirkham** [comment]
The email on that last commit is incorrect. Can you please correct this, @sannykr? GitHub has some nice [docs]( https://help.github.com/articles/setting-your-commit-email-address-in-git/ ) explaining how.

**Pull request closed without merging**
